-- MySQL Script generated by MySQL Workbench
-- Tue May  7 07:35:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS ARMARIODIGITAL;

CREATE DATABASE IF NOT EXISTS ARMARIODIGITAL;

USE ARMARIODIGITAL;

-- -----------------------------------------------------
-- Table Funcionarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Funcionarios (
    idFuncionarios INT NOT NULL,
    Salario DECIMAL(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    NomeFuncionario VARCHAR(45) NOT NULL,
    Login VARCHAR(30) NOT NULL,
    Senha VARCHAR(15) NOT NULL,
    PRIMARY KEY (idFuncionarios)
);

-- -----------------------------------------------------
-- Table Fornecedores
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Fornecedores (
    idFornecedores INT NOT NULL,
    Email VARCHAR(40) NOT NULL,
    Nome_Fornecedor VARCHAR(45) NOT NULL,
    Nome_Ctt VARCHAR(45) NOT NULL,
    Telefone VARCHAR(45) NOT NULL,
    PRIMARY KEY (idFornecedores)
);

-- -----------------------------------------------------
-- Table Produtos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Produtos (
    idProdutos INT NOT NULL,
    Tamanho VARCHAR(10) NOT NULL,
    Categoria VARCHAR(30) NOT NULL,
    Preco DECIMAL(30) NOT NULL,
    QT_Estoque INT NOT NULL,
    Cor VARCHAR(30) NOT NULL,
    Marca VARCHAR(30) NOT NULL,
    ID_Fornecedor INT NOT NULL,
    Fornecedores_idFornecedores INT NOT NULL,
    PRIMARY KEY (idProdutos),
    FOREIGN KEY (Fornecedores_idFornecedores) REFERENCES Fornecedores (idFornecedores)
);

-- -----------------------------------------------------
-- Table Cliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Clientes (
    idCliente INT NOT NULL,
    Nome_Clientes VARCHAR(45) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    Email VARCHAR(40) NOT NULL,
    Telefone VARCHAR(30) NOT NULL,
    PRIMARY KEY (idCliente)
);

-- -----------------------------------------------------
-- Table Vendas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Vendas (
    idVendas INT NOT NULL,
    Hora_venda TIME(6) NOT NULL,
    Quantidade INT NOT NULL,
    MTD_Pagamento VARCHAR(30) NOT NULL,
    Funcionarios_idFuncionarios INT NOT NULL,
    Cliente_idCliente1 INT NOT NULL,
    PRIMARY KEY (idVendas),
    FOREIGN KEY (Funcionarios_idFuncionarios) REFERENCES Funcionarios (idFuncionarios),
    FOREIGN KEY (Cliente_idCliente1) REFERENCES Clientes (idCliente)
);

-- -----------------------------------------------------
-- Table Carrinho
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Carrinho (
    ID_Carrinho INT NOT NULL,
    Vendas_idVendas INT NOT NULL,
    Produtos_idProdutos INT NOT NULL,
    Quantidade INT NOT NULL,
    PRIMARY KEY (ID_Carrinho),
    FOREIGN KEY (Vendas_idVendas) REFERENCES Vendas (idVendas),
    FOREIGN KEY (Produtos_idProdutos) REFERENCES Produtos (idProdutos)
);